server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      db-type: MySQL
      # 数据库访问配置, 使用druid数据源
      url: jdbc:mysql://172.20.200.112:3306/blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: root
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat
      # Spring监控AOP切入点，如 x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.oneself.blog.*.service.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/actuator/*'

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的bean的时候，是否允许覆盖注册到容器

  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 0
    #配置redisson
    redisson:
      config: classpath:redisson/redisson-dev.yml #配置集群模式
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true
  cache:
    type:
      redis



mybatis-plus:
  global-config:
    #刷新Mapper，只在开发环境打开
    refresh: true
  # mapper xml实现扫描路径
  mapper-locations: classpath*:mapper/**/*.xml,classpath*:mapper/**/**/*.xml,classpath*:mapper/**/**/**/*.xml
  configuration:
    jdbc-type-for-null: null

#分页插件配置
pagehelper:
  #数据库名称
  helperDialect: mysql
  #分页参数合理化，默认值为false。当此参数设置为时true， pageNum <= 0将查询第一页， PageNum> pages（超过总数），将查询最后一页。默认情况下false，查询直接基于参数。
  reasonable: true
  #支持通过Mapper接口参数传递page参数
  supportMethodsArguments: true
  #在支持startPage(Object params)方法时，添加参数以根据属性名称配置参数映射为对象的值，可以配置pageNum,pageSize,count,pageSizeZero,reasonable，默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  params: count=countSql


# blog-config 配置
blog-config:
  # 是否在控制台打印 sql语句
  showsql: true
  # 时间类型参数在前端页面的展示格式，默认格式为 yyyy-MM-dd HH:mm:ss
  timeFormat: yyyy-MM-dd HH:mm:ss
  # 是否开启 AOP 日志，默认开启
  openAopLog: true

  shiro:
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认86400秒，即一天
    cookieTimeout: 86400
    # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    anonUrl: /register,/css/**,/js/**,/fonts/**,/img/**,/druid/**,/user/regist,/gifCode,/,/actuator/**,/test/**,/swagger-ui.html,/webjars/**,/v2/**,/swagger-resources/**
    # 登录 url
    loginUrl: /login
    # 登录成功后跳转的 url
    successUrl: /index
    # 登出 url
    logoutUrl: /logout
    # 未授权跳转 url
    unauthorizedUrl: /403
    # sessionId
    sessionid: blog_sessionId
#rocketmq:
#  groupName: rocketmq
#  namesrvAddr: 192.168.250.2:9876
